server:
  port: 4000
spring:
  application:
    name: atguigu-crowd-auth
  redis:
      host: 192.168.247.131
  session:
      store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
short:
  message:
    app-code: c7a7ac7c67324f9ea8caebe34af2ac2b
    host: https://gyytz.market.alicloudapi.com
    method: POST
    path: /sms/smsSend
    sign: 2e65b1bb3d054466b82f0c9d125465e2
    skin: 908e94ccf08b4476ba6c876d13f084ad
ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000